sonar.projectKey=Frappe
sonar.projectName=Frappe
sonar.projectVersion=1.0
sonar.sources=frappe
sonar.language=python
sonar.sourceEncoding=UTF-8
sonar.host.url=http://docker-compose-jenkins-sonarqube_sonarqube_1:9001
sonar.login=sqa_5aaccfe297e68a56b61d84be26a6bd36c875c603